
1:
	@echo "创建窗口"
	@gcc `pkg-config --cflags gtk+-3.0` -o example-0 example-0.c `pkg-config --libs gtk+-3.0`
	./example-0

2:
	@echo "部件的添加"
	@gcc `pkg-config --cflags gtk+-3.0` -o example-1 example-1.c `pkg-config --libs gtk+-3.0`
	./example-1

3:
	@echo "表格的使用"
	@gcc `pkg-config --cflags gtk+-3.0` -o example-2 example-2.c `pkg-config --libs gtk+-3.0`
	./example-2

4:
	@echo "用户接口xml"
	@gcc `pkg-config --cflags gtk+-3.0` -o example-4 example-4.c `pkg-config --libs gtk+-3.0`
	./example-4
5:
	@echo "另一种窗口创建"
	@gcc `pkg-config --cflags gtk+-3.0` -o example-5 example-5.c `pkg-config --libs gtk+-3.0`
	./example-5

test:
	@gcc `pkg-config --cflags gtk+-3.0` -o test test.c `pkg-config --libs gtk+-3.0`

