#! /bin/bash




export USER=lfs
export LFS=/mnt/lfs

sudo apt install gawk texinfo

#groupadd lfs
#useradd -s /bin/bash -g lfs -m -k /dev/null lfs
#passwd $USER

mkdir -pv $LFS
mount -v -t ext4 /dev/sdd2 $LFS/
chmod -v a+wt $LFS
chown -v $USER $LFS

cd ~
svn co svn://svn.linuxfromscratch.org/ALFS/jhalfs/tags/2.4 jhalfs-2.4
cd jhalfs-2.4

mkdir -pv $LFS/{dev,proc,sys,run}
mknod -m 600 $LFS/dev/console c 5 1
mknod -m 666 $LFS/dev/null c 1 3
mount -v --bind /dev $LFS/dev
mount -vt devpts devpts $LFS/dev/pts -o gid=5,mode=620
mount -vt proc proc $LFS/proc
mount -vt sysfs sysfs $LFS/sys
mount -vt tmpfs tmpfs $LFS/run
if [ -h $LFS/dev/shm ]; then
  mkdir -pv $LFS/$(readlink $LFS/dev/shm)
fi


chroot "$LFS" /tools/bin/env -i \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='\u:\w\$ '              \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
    /tools/bin/bash --login +h


#clocksource=acpi_pm
